version: '3.8'
services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/password.txt:/mosquitto/config/password.txt
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - default
  node-web:
    build:
      context: ./node-web
      dockerfile: Dockerfile
    depends_on: 
      - mqtt-broker
    volumes: 
      - /app/node_modules
      - ./node-web:/app 
    ports: 
      - "3000:3000"
    networks:
      - default
networks:
  default:
    driver: bridge
